// SPDX-FileCopyrightText: 2024 KUSANAGI Mitsuhisa <mikkun@mbg.nifty.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#include <SDL2/SDL_mixer.h>

/* Enable API */
#define DEFAULT_SDL_MIXER_MAJOR_VERSION SDL_MIXER_MAJOR_VERSION
#define DEFAULT_SDL_MIXER_MINOR_VERSION SDL_MIXER_MINOR_VERSION
#define DEFAULT_SDL_MIXER_PATCHLEVEL SDL_MIXER_PATCHLEVEL
#define DEFAULT_MIX_DEFAULT_FREQUENCY MIX_DEFAULT_FREQUENCY
#define DEFAULT_MIX_DEFAULT_FORMAT MIX_DEFAULT_FORMAT
#define DEFAULT_MIX_DEFAULT_CHANNELS MIX_DEFAULT_CHANNELS
#define DEFAULT_MIX_MAX_VOLUME MIX_MAX_VOLUME
#define DEFAULT_AUDIO_U16SYS AUDIO_U16SYS
#define DEFAULT_AUDIO_S16SYS AUDIO_S16SYS
#define DEFAULT_AUDIO_S32SYS AUDIO_S32SYS
#define DEFAULT_AUDIO_F32SYS AUDIO_F32SYS

#define ENTRY(VAR, CONST)                       \
    {                                           \
        &VAR##_node, #VAR, DEFAULT_##VAR, CONST \
    }

#define NUM_SCALARS (sizeof(varinit) / sizeof(varinit[0]))
#define NUM_RESET (NUM_SCALARS - 1)
